"""add_skill_assessment_tables

Revision ID: 3c6620ed001c
Revises: add_newsletter_subscription
Create Date: 2025-12-13 09:50:23.828866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6620ed001c'
down_revision: Union[str, None] = 'add_newsletter_subscription'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###