"""add_billing_cycle_and_pricing_url

Revision ID: a7ff7ed5c8c4
Revises: add_user_subscriptions
Create Date: 2025-12-14 09:16:09.545201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7ff7ed5c8c4'
down_revision: Union[str, None] = 'add_user_subscriptions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_subscriptions_category', table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_id', table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_user_id', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('ENTERTAINMENT', 'AI_TOOLS', 'DEV_TOOLS', 'DESIGN_CREATIVE', 'PRODUCTIVITY', 'CLOUD_STORAGE', 'FITNESS_HEALTH', 'EDUCATION', 'OTHER', name='subscriptioncategory'), autoincrement=False, nullable=False),
    sa.Column('monthly_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'INR'::character varying"), autoincrement=False, nullable=False),
    sa.Column('usage_frequency', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'RARELY', 'FORGOT', name='usagefrequency'), autoincrement=False, nullable=False),
    sa.Column('is_custom', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_subscriptions_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_subscriptions_pkey')
    )
    op.create_index('ix_user_subscriptions_user_id', 'user_subscriptions', ['user_id'], unique=False)
    op.create_index('ix_user_subscriptions_id', 'user_subscriptions', ['id'], unique=False)
    op.create_index('ix_user_subscriptions_category', 'user_subscriptions', ['category'], unique=False)
    # ### end Alembic commands ###