"""create_skill_assessment_tables_fixed

Revision ID: c5a809da75a6
Revises: 3c6620ed001c
Create Date: 2025-12-13 10:30:52.152222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a809da75a6'
down_revision: Union[str, None] = '3c6620ed001c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sa_skill_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_skill_assessments_id'), 'sa_skill_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_sa_skill_assessments_topic'), 'sa_skill_assessments', ['topic'], unique=False)
    op.create_index(op.f('ix_sa_skill_assessments_user_id'), 'sa_skill_assessments', ['user_id'], unique=False)
    op.create_table('sa_learning_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('plan_content', sa.JSON(), nullable=False),
    sa.Column('timeline_weeks', sa.Integer(), nullable=True),
    sa.Column('priority_skills', sa.JSON(), nullable=False),
    sa.Column('recommended_resources', sa.JSON(), nullable=False),
    sa.Column('project_ideas', sa.JSON(), nullable=True),
    sa.Column('market_trends', sa.JSON(), nullable=True),
    sa.Column('export_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['sa_skill_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_learning_plans_assessment_id'), 'sa_learning_plans', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_sa_learning_plans_id'), 'sa_learning_plans', ['id'], unique=False)
    op.create_table('sa_quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.String(length=500), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['sa_skill_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_quiz_questions_assessment_id'), 'sa_quiz_questions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_sa_quiz_questions_id'), 'sa_quiz_questions', ['id'], unique=False)
    op.create_table('sa_skill_evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('expertise_level', sa.String(length=20), nullable=False),
    sa.Column('detailed_analysis', sa.JSON(), nullable=True),
    sa.Column('market_insights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['sa_skill_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_skill_evaluation_results_assessment_id'), 'sa_skill_evaluation_results', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_sa_skill_evaluation_results_id'), 'sa_skill_evaluation_results', ['id'], unique=False)
    op.create_table('sa_quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['sa_quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sa_quiz_answers_id'), 'sa_quiz_answers', ['id'], unique=False)
    op.create_index(op.f('ix_sa_quiz_answers_question_id'), 'sa_quiz_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sa_quiz_answers_question_id'), table_name='sa_quiz_answers')
    op.drop_index(op.f('ix_sa_quiz_answers_id'), table_name='sa_quiz_answers')
    op.drop_table('sa_quiz_answers')
    op.drop_index(op.f('ix_sa_skill_evaluation_results_id'), table_name='sa_skill_evaluation_results')
    op.drop_index(op.f('ix_sa_skill_evaluation_results_assessment_id'), table_name='sa_skill_evaluation_results')
    op.drop_table('sa_skill_evaluation_results')
    op.drop_index(op.f('ix_sa_quiz_questions_id'), table_name='sa_quiz_questions')
    op.drop_index(op.f('ix_sa_quiz_questions_assessment_id'), table_name='sa_quiz_questions')
    op.drop_table('sa_quiz_questions')
    op.drop_index(op.f('ix_sa_learning_plans_id'), table_name='sa_learning_plans')
    op.drop_index(op.f('ix_sa_learning_plans_assessment_id'), table_name='sa_learning_plans')
    op.drop_table('sa_learning_plans')
    op.drop_index(op.f('ix_sa_skill_assessments_user_id'), table_name='sa_skill_assessments')
    op.drop_index(op.f('ix_sa_skill_assessments_topic'), table_name='sa_skill_assessments')
    op.drop_index(op.f('ix_sa_skill_assessments_id'), table_name='sa_skill_assessments')
    op.drop_table('sa_skill_assessments')
    # ### end Alembic commands ###